language: ruby

rvm:
  - 2.1.5

sudo: false

cache: bundler

env:
  global:
    - RUN=1

before_install:
  - echo "set up credential.helper"; git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_OAUTH_TOKEN}:@github.com" > .git/credentials 2>/dev/null
  - echo "set up user.email"; git config --global user.email "contact@travis-ci.com"
  - echo "set up user.name"; git config --global user.name "Travis CI APT package tester"

script:
  - bundle exec ./run_tests.rb

notifications:
  email: false
