language: ruby

sudo: required

dist: trusty

git:
  depth: 99999

env:
  global:
    - DEBIAN_FRONTEND=noninteractive
    - PACKAGE=libdc1394-22-dev
    - ISSUE_REPO=apt-package-whitelist
    - ISSUE_NUMBER=3394

before_install:
  - if [ -z $PACKAGE ]; then echo "\$PACKAGE not defined" && travis_terminate 2; fi
  - sudo apt-get update -y -qq
  - sudo apt-get install -yqq sshpass
  - if ! command -v docker ; then curl -sSL https://get.docker.io | bash; fi
  - sudo usermod -a -G docker travis
  - docker pull quay.io/travisci/travis-node-js:latest
  - jq --version || sudo curl -sSL -o /usr/local/bin/jq http://stedolan.github.io/jq/download/linux64/jq && sudo chmod 0755 /usr/local/bin/jq
  - docker images | grep -q -E '^travis\\s+\\bnode-js\\b\\s+' || docker tag quay.io/travisci/travis-node-js:latest travis:node-js
  - docker run -v /var/tmp:/var/tmp -v /home/travis/build:/home/travis/build -d travis:node-js | tee docker_id
  - docker inspect $(< docker_id) | jq -r .[0].NetworkSettings.IPAddress | tee docker_ip_address
  - docker ps
  - ruby -rsocket -rtimeout -e "Timeout::timeout(30) { TCPSocket.new('$(< docker_ip_address)',22) }"

install:
  - true

script:
  - ./run_test.sh

notifications:
  email: false
