language: bash

sudo: 9000

dist: trusty

env:
  global:
    - DEBIAN_FRONTEND=noninteractive

before_install:
  - if [ -z $PACKAGE ]; then echo "\$PACKAGE not defined" && travis_terminate 2; fi
  - pushd ..
  - git clone https://github.com/travis-ci/apt-package-whitelist.git
  - popd
  - sudo apt-get update -y -qq
  - sudo apt-get install -yqq lvm2 xfsprogs sshpass
  - if ! command -v docker ; then curl -sSL https://get.docker.io | bash; fi
  - sudo usermod -a -G docker travis
  - docker pull quay.io/travisci/travis-ruby:latest
  - jq --version || sudo curl -sSL -o /usr/local/bin/jq http://stedolan.github.io/jq/download/linux64/jq && sudo chmod 0755 /usr/local/bin/jq
  - docker images | grep -q -E '^travis\\s+\\bruby\\b\\s+' || docker tag quay.io/travisci/travis-ruby:latest travis:ruby
  - docker run -v /var/tmp:/var/tmp -v /home/travis/build:/home/travis/build -d travis:ruby | tee docker_id
  - docker inspect $(< docker_id)
  - docker inspect $(< docker_id) | awk -F '"' '/IPAddress/ {print $4}' | tee docker_ip_address
  - docker ps
  - sleep 10

install:
  - true

script:
>
  echo -e "export PS1='$ '         \n
  export DEBIAN_FRONTEND=noninteractive \n
  wget https://raw.githubusercontent.com/travis-ci/apt-source-whitelist/master/ubuntu.json \n
  ruby -rjson -e 'json=JSON.parse(File.read("ubuntu.json")); json.each {|src| system "curl -sSL #{src["key_url"]} | sudo apt-key add -" if src["key_url"]; system "sudo -E apt-add-repository -y #{src["sourceline"]}" }' \n
  mkdir -p /var/tmp/deb-sources    \n
  cd /var/tmp/deb-sources          \n
  sudo apt-get update -qq          \n
  apt-get source ${PACKAGE}        \n
  grep -R -i -E 'set(uid|euid|gid)' . 2>/dev/null || echo -e '\n\nno setuid bits found\n\n' \n
  exit                             \n" | sshpass -p travis ssh -t -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no travis@$(< docker_ip_address)

notifications:
  email: false
