language: ruby

sudo: required

dist: trusty

git:
  depth: 99999

env:
  global:
    - DEBIAN_FRONTEND=noninteractive
    - PACKAGE=g++-7
    - ISSUE_REPO=apt-package-whitelist
    - ISSUE_NUMBER=4217
    - DIST=trusty

before_install:
  - if [ -z $PACKAGE ]; then echo "\$PACKAGE not defined" && travis_terminate 2; fi
  - if ! command -v docker ; then curl -sSL https://get.docker.io | bash; fi
  - "[[ $DIST = 'precise' ]] && echo \"$DIST is no longer supported.\" && travis_terminate 1"
  - jq --version || sudo curl -sSL -o /usr/local/bin/jq http://stedolan.github.io/jq/download/linux64/jq && sudo chmod 0755 /usr/local/bin/jq

install:
  - true

script:
  - ./run_test.sh

notifications:
  email: false
