language: ruby

sudo: required

dist: trusty

before_install:
  - echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install virtualbox-5.0 > virtualbox-install.log
  - sudo apt-get install linux-headers-3.16.0-30-generic > linux-headers-install.log
  - sudo /etc/init.d/vboxdrv setup
  - VBoxManage --version
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb -O vagrant.deb
  - sudo dpkg -i vagrant.deb

install:
  - git clone https://github.com/travis-ci/apt-package-whitelist.git
  - pushd apt-package-whitelist
  - vagrant up

script:
  - true

notifications:
  email: false
