language: ruby

sudo: required

dist: trusty

before_install:
  - echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install virtualbox-5.0 > virtualbox-install.log

install:
  - true

script:
  - true
