language: ruby

sudo: 9000

env:
  global:
    - DEBIAN_FRONTEND=noninteractive

before_install:
  - if [ -z $PACKAGE ]; then echo "\$PACKAGE not defined" && travis_terminate 2; fi
  - if ! command -v docker ; then curl -sSL https://get.docker.io | bash; fi
  - sudo usermod -a -G docker travis
  - docker pull stackbrew/ubuntu:12.04
  - jq --version || sudo curl -sSL -o /usr/local/bin/jq http://stedolan.github.io/jq/download/linux64/jq && sudo chmod 0755 /usr/local/bin/jq
  - docker run -v /var/tmp:/var/tmp -v /home/travis/build:/home/travis/build -d stackbrew/ubuntu:12.04 | tee docker_id
  - docker ps

install:
  - true

script:
  - ./run_test.sh

notifications:
  email: false
